# `dependabot.yml` file with updates
# disabled for Docker and limited for npm

version: 2
updates:
    directory: "/"
    schedule:
      interval: "weekly"
      # Disable all pull requests for Docker dependencies
    open-pull-requests-limit: 1000
